export { default as Blogs } from './blogs/Blogs'
export { default as ContactUs } from './contactUs/ContactUs'
export { default as Header } from './header/Header'
export { default as Footer } from './footer/Footer'
export { default as OurTeam } from './ourTeam/OurTeam'
export { default as WhyChooseUs } from './whyChooseUs/WhyChooseUs'